website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.dialects.sqlite import BLOB

favourites = db.Table('favourites',
    db.Column('user_id', db.Integer, db.ForeignKey('user.id'), primary_key=True),
    db.Column('data_id', db.Integer, db.ForeignKey('data.id'), primary_key=True)
)

class Group(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150))
    description = db.Column(db.Text)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = db.relationship('User', backref=db.backref('created_groups', lazy=True))
    recipes = db.relationship('Data', backref='group', lazy=True)
    public = db.Column(db.Boolean)

class Data(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    group_id = db.Column(db.Integer, db.ForeignKey('group.id'), nullable=False)
    cooking_time = db.Column(db.Integer, nullable=False)
    difficulty_level = db.Column(db.String, nullable=False)
    recipe = db.Column(db.String(10000))
    image_path = db.Column(db.Text)
    ingredients = db.relationship('Ingredient', backref='data', lazy=True)
    instructions = db.Column(db.Text)
    recipe_type = db.Column(db.String, nullable=False)
    public = db.Column(db.Boolean, default=False)
    reviews = db.relationship('Review', backref='recipe', lazy=True)
    comments = db.relationship('Comment', backref='recipe', lazy=True)
    favourited_by = db.relationship('User', secondary=favourites, backref=db.backref('favourites', lazy='dynamic'))

class Ingredient(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    quantity = db.Column(db.String(100), nullable=False)
    name = db.Column(db.String(100), nullable=False)
    data_id = db.Column(db.Integer, db.ForeignKey('data.id'), nullable=False)

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(150), unique=True, nullable=False)
    email = db.Column(db.String(150), unique=True, nullable=False)
    password = db.Column(db.String(150), nullable=False)
    recipes = db.relationship('Data', backref='user', lazy=True)
    groups = db.relationship('Group', backref='creator', lazy=True)
    shopping_list = db.Column(db.Text, nullable=True)
    reviews = db.relationship('Review', backref='user', lazy=True)
    comments = db.relationship('Comment', backref='user', lazy=True)

class Review(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    thumbs_up = db.Column(db.Boolean)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    recipe_id = db.Column(db.Integer, db.ForeignKey('data.id'), nullable=False)


class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    recipe_id = db.Column(db.Integer, db.ForeignKey('data.id'), nullable=False)

website/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_migrate import Migrate
from sqlalchemy.dialects.sqlite import BLOB

db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__, static_folder='static')
 
    app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY', 'fallback_secret_key')
    app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('DATABASE_URL', r'sqlite:///C:\Users\Shriya.Kela\recipeapp\website\dbScript\app.db')
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False  # Add this line to suppress a warning
    app.config['UPLOAD_FOLDER'] = 'static/uploads'
    

    db.init_app(app)
    migrate = Migrate(app, db)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User

    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from flask_login import login_required, current_user
from .models import Data, User, Group, Ingredient,Review, Comment,favourites
from werkzeug.utils import secure_filename
from . import db
import os
from flask import current_app

views = Blueprint('views', __name__)

@views.route('/')
@login_required
def home():
    # Get all public groups
    public_groups = Group.query.filter_by(public=True).all()
    
    
    # user_groups = Group.query.filter((Group.user_id == current_user.id) | (Group.public == True)).all()

    
    # unique_groups = {group.id: group for group in user_groups}.values()
    
    
    public_recipes = Data.query.join(Group).filter(Group.public == True).all()

    return render_template("home.html", user=current_user, groups=public_groups, public_recipes=public_recipes)


@views.route('/group/<int:group_id>')
@login_required
def group_recipes(group_id):
    group = Group.query.get_or_404(group_id)
    
    # Check if the group is public or if the user is the creator of the group
    if not group.public and group.user_id != current_user.id:
        flash('You do not have permission to view this group!', category='error')
        return redirect(url_for('views.home'))

    # Get recipes for the group
    recipes = Data.query.filter_by(group_id=group_id).all()
    
    return render_template("group_recipes.html", user=current_user, group=group, recipes=recipes)
@views.route('/create-group', methods=['GET', 'POST'])
@login_required
def create_group():
    if request.method == 'POST':
        name = request.form.get('name')
        description = request.form.get('description')
        public = 'public' in request.form  # This will be True if the 'public' checkbox is checked

        if len(name) < 1:
            flash('Group name is too short!', category='error')
        else:
            new_group = Group(name=name, description=description, user_id=current_user.id, public=public)
            db.session.add(new_group)
            db.session.commit()
            flash('Group created!', category='success')
            return redirect(url_for('views.home'))

    return render_template('create_group.html', user=current_user)


@views.route('/edit-group/<int:group_id>', methods=['GET', 'POST'])
@login_required
def edit_group(group_id):
    group = Group.query.get_or_404(group_id)
    if group.user_id != current_user.id:
        flash('You do not have permission to edit this group.', 'danger')
        return redirect(url_for('views.home'))

    if request.method == 'POST':
        group.name = request.form.get('name')
        group.description = request.form.get('description')
        group.public = 'public' in request.form
        db.session.commit()
        flash('Group has been updated!', 'success')
        return redirect(url_for('views.home'))

    return render_template('edit_group.html', group=group, user=current_user)





@views.route('/delete-group/<int:group_id>', methods=['POST'])
@login_required
def delete_group(group_id):
    group = Group.query.get_or_404(group_id)
    if group and group.user_id == current_user.id:
        # Delete related recipes
        Data.query.filter_by(group_id=group_id).delete()
        db.session.delete(group)
        db.session.commit()
        flash('Group deleted!', category='success')
    else:
        flash('You do not have permission to delete this group!', category='error')
    return redirect(url_for('views.home'))

# @views.route('/add-recipe/<int:group_id>', methods=['GET', 'POST'])
# @login_required
# def add_recipe(group_id):
#     if group_id is None:
#         flash('Please select a group to add a recipe to.', category='error')
#         return redirect(url_for('views.home'))

#     group = Group.query.get_or_404(group_id)
#     # if group.user_id != current_user.id:
#     #     flash('You do not have permission to add recipes to this group!', category='error')
#     #     return redirect(url_for('views.home'))

#     if request.method == 'POST':
#         recipe_name = request.form.get('name')
#         ingredient_quantities = request.form.getlist('ingredient_quantities[]')
#         ingredient_names = request.form.getlist('ingredient_names[]')
#         instructions = request.form.get('instructions')
#         recipe_image = request.files.get('image')
#         cooking_time = request.form.get('cooking_time')
#         difficulty_level = request.form.get('difficulty_level')
#         recipe_type = request.form.get('recipe_type')
#         public= request.form.get('public')

#         if not recipe_name or not ingredient_names or not instructions:
#             flash('Recipe name, ingredients, and instructions are required!', category='error')
#             return redirect(url_for('views.add_recipe', group_id=group_id))

#         if recipe_image:
#             filename = secure_filename(recipe_image.filename)
#             static_folder = os.path.join(current_app.root_path, 'static')
#             if not os.path.exists(static_folder):
#                 os.makedirs(static_folder)
#             image_path = os.path.join(static_folder, filename)
#             recipe_image.save(image_path)
#             relative_image_path = os.path.join('static', filename)
#         else:
#             relative_image_path = None

#         new_recipe = Data(
#             recipe=recipe_name,
#             image_path=relative_image_path,
#             instructions=instructions,
#             user_id=current_user.id,
#             public=True,
#             group_id=group_id,
#             cooking_time=cooking_time,
#             difficulty_level=difficulty_level,
#             recipe_type=recipe_type
#         )
#         db.session.add(new_recipe)
#         db.session.commit()

#         for quantity, name in zip(ingredient_quantities, ingredient_names):
#             new_ingredient = Ingredient(quantity=quantity, name=name, data_id=new_recipe.id)
#             db.session.add(new_ingredient)

#         db.session.commit()
#         flash(f'Recipe added to {group.name}!', category='success')
#         return redirect(url_for('views.group_recipes', group_id=group_id))

#     return render_template('add_recipe.html', user=current_user, group=group)
@views.route('/add-recipe/<int:group_id>', methods=['GET', 'POST'])
@login_required
def add_recipe(group_id):
    if group_id is None:
        flash('Please select a group to add a recipe to.', category='error')
        return redirect(url_for('views.home'))

    group = Group.query.get_or_404(group_id)

    if request.method == 'POST':
        recipe_name = request.form.get('name')
        ingredient_quantities = request.form.getlist('ingredient_quantities[]')
        ingredient_names = request.form.getlist('ingredient_names[]')
        instructions = request.form.get('instructions')
        recipe_image = request.files['recipe_image']
        cooking_time = request.form.get('cooking_time')
        difficulty_level = request.form.get('difficulty_level')
        recipe_type = request.form.get('recipe_type')
        public = request.form.get('public')

        if not recipe_name or not ingredient_names or not instructions:
            flash('Recipe name, ingredients, and instructions are required!', category='error')
            return redirect(url_for('views.add_recipe', group_id=group_id))

        image_path = None
        if recipe_image:
            filename = secure_filename(recipe_image.filename)
            upload_folder = os.path.join(current_app.root_path, current_app.config['UPLOAD_FOLDER'])
            if not os.path.exists(upload_folder):
                os.makedirs(upload_folder)
            filepath = os.path.join(upload_folder, filename)
            recipe_image.save(filepath)
            image_path =  filename  # Store the path relative to static folder
            flash('Image saved successfully')

        new_recipe = Data(
            recipe=recipe_name,
            image_path=image_path,  # Save the relative image path to the database
            instructions=instructions,
            user_id=current_user.id,
            public=True if public else False,
            group_id=group_id,
            cooking_time=cooking_time,
            difficulty_level=difficulty_level,
            recipe_type=recipe_type
        )
        db.session.add(new_recipe)
        db.session.commit()

        for quantity, name in zip(ingredient_quantities, ingredient_names):
            new_ingredient = Ingredient(quantity=quantity, name=name, data_id=new_recipe.id)
            db.session.add(new_ingredient)

        db.session.commit()
        flash(f'Recipe added to {group.name}!', category='success')
        return redirect(url_for('views.group_recipes', group_id=group_id))

    return render_template('add_recipe.html', user=current_user, group=group)
from flask import abort

@views.route('/delete_recipe/<int:recipe_id>', methods=['POST'])
@login_required
def delete_recipe(recipe_id):
    recipe = Data.query.get_or_404(recipe_id)
    
    if recipe.user_id != current_user.id:
        abort(403)  # Forbidden

    try:
        # First, delete all ingredients associated with this recipe
        Ingredient.query.filter_by(data_id=recipe.id).delete()
        
        # Then delete the recipe
        db.session.delete(recipe)
        db.session.commit()
        flash('Recipe deleted successfully!', category='success')
    except Exception as e:
        db.session.rollback()
        flash(f'An error occurred while deleting the recipe: {str(e)}', category='error')
    
    return redirect(url_for('views.group_recipes', group_id=recipe.group_id))



@views.route('/edit-recipe/<int:recipe_id>', methods=['GET', 'POST'])
@login_required
def edit_recipe(recipe_id):
    recipe = Data.query.get_or_404(recipe_id)
    if recipe.user_id != current_user.id:
        flash('You do not have permission to edit this recipe!', category='error')

website/templates/add_recipe.html
{% extends "base.html" %}
{% block content %}
<h1>Add Recipe</h1>
<form method="POST" enctype="multipart/form-data">
    <div class="form-group">
        <label for="name">Recipe Name:</label>
        <input type="text" class="form-control" id="name" name="name" required>
    </div>

    <div id="ingredient-container">
        <div class="ingredient-item">
            <input type="text" name="ingredient_quantities[]" placeholder="Quantity" required>
            <input type="text" name="ingredient_names[]" placeholder="Ingredient Name" required>
        </div>
    </div>
    <button type="button" id="add-ingredient">Add Ingredient</button>

    <div class="form-group">
        <label for="instructions">Instructions:</label>
        <textarea class="form-control" id="instructions" name="instructions" required></textarea>
    </div>

    <div class="form-group">
        <label for="recipe_image">Recipe Image:</label>
        <input type="file" class="form-control-file" id="recipe_image" name="recipe_image">
    </div>

    <div class="form-group">
        <label for="cooking_time">Cooking Time (minutes):</label>
        <input type="number" class="form-control" id="cooking_time" name="cooking_time" required>
    </div>

    <div class="form-group">
        <label for="difficulty_level">Difficulty Level:</label>
        <select class="form-control" id="difficulty_level" name="difficulty_level" required>
            <option value="Easy">Easy</option>
            <option value="Medium">Medium</option>
            <option value="Hard">Hard</option>
        </select>
    </div>

    <div class="form-group">
        <label for="recipe_type">Recipe Type:</label>
        <select class="form-control" id="recipe_type" name="recipe_type" required>
            <option value="Vegetarian">Vegetarian</option>
            <option value="Non-Vegetarian">Non-Vegetarian</option>
            <option value="Vegan">Vegan</option>
        </select>
    </div>
    <div class="form-check mb-3">
        <input class="form-check-input" type="checkbox" id="public" name="public" checked>
        <label class="form-check-label" for="public">
            Public Group
        </label>
    </div>

    <button type="submit" class="btn btn-primary">Add Recipe</button>
</form>

<script>
document.getElementById('add-ingredient').addEventListener('click', function() {
    var container = document.getElementById('ingredient-container');
    var newItem = document.createElement('div');
    newItem.className = 'ingredient-item';
    newItem.innerHTML = `
        <input type="text" name="ingredient_quantities[]" placeholder="Quantity" required>
        <input type="text" name="ingredient_names[]" placeholder="Ingredient Name" required>
    `;
    container.appendChild(newItem);
});
</script>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}FlaskApp{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Recipe App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/logout">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('views.profile') }}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('views.dashboard') }}">Dashboard</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/signup">Signup</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ 'danger' if category == 'error' else 'success' }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
</body>
</html>

website/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <style>
        /* Navbar Styling */
  .navbar {
    background-color: rgba(247, 239, 239, 0.7) !important;
  }
  
  .navbar-brand {
    color: #fff;
    font-size: 1.5rem;
  }
  
  .navbar-nav .nav-link {
    color: #0f0f0f !important;
    margin-right: 15px;
  }
  
  .navbar-nav .nav-link:hover {
    color: #f0f0f0 !important;
  }
  
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Recipe App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                
                    <li class="nav-item">
                        <a class="nav-link" href="/logout">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('views.profile') }}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('views.dashboard') }}">Profile</a>
                    </li>
                
            </ul>
        </div>
    </nav>
    

    <div class="carousel">
        <div class="list">
            <div class="item active" style="--background: #EA3D41">
                <div class="content">Strawberry</div>
                <img src="{{ url_for('static', filename='img/fruit_strawberry.png') }}" class="fruit">
            </div>
            <div class="item" style="--background: #2D5643">
                <div class="content">Avocado</div>
                <img src="{{ url_for('static', filename='img/fruit_avocado.png') }}" class="fruit">
            </div>
            <div class="item hidden" style="--background: #E7A043">
                <div class="content">Orange</div>
                <img src="{{ url_for('static', filename='img/fruit_orange.png') }}" class="fruit">
            </div>
        </div>
        <div class="leaves"></div>
        <div class="mockup"></div>
        <div class="shadow"></div>
        <div class="arrow">
            <button id="prev"><</button>
            <button id="next">></button>
        </div>
    </div>

    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
</body>
</html>

website/templates/group_recipes.html
{% extends "base.html" %}
{% block title %}Group Recipes{% endblock %}
{% block content %}
<div>
    <h1>{{ group.name }}</h1>
    <p>{{ group.description }}</p>
    {% if group.public or group.user_id == current_user.id %}
    <a href="{{ url_for('views.add_recipe', group_id=group.id) }}" class="btn btn-primary">Add Recipe</a>
    {% endif %}
</div>
<div class="recipe-list">
    <h2>Recipes in this Group</h2>
    {% for recipe in recipes %}
    <div class="recipe-card">
        <h3>{{ recipe.recipe }}</h3>
        {% if recipe.image_path %}
        <img src="http://127.0.0.1:5000/static/{{recipe.image_path }}" alt="{{ recipe.recipe }}" class="img-fluid">
    {% endif %}
        <!-- <p>{{ recipe.ingredients }}</p>
        <p>{{ recipe.instructions }}</p> -->
        {% if recipe.user_id == current_user.id %}
        <a href="{{ url_for('views.edit_recipe', recipe_id=recipe.id) }}" class="btn btn-warning">Edit</a>
        <form action="{{ url_for('views.delete_recipe', recipe_id=recipe.id) }}" method="POST" style="display:inline;">
            <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this recipe?');">Delete</button>
        </form>
        {% endif %}
        <a href="{{ url_for('views.recipe_detail', recipe_id=recipe.id) }}" class="btn btn-primary">View Recipe</a>
    </div>
    {% endfor %}
</div>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}

<div class="container">
  <h1 class="text-center mb-4">Welcome to Your Recipe Dashboard</h1>
  
  <div class="text-center mb-4">
    <a href="{{ url_for('views.create_group') }}" class="btn btn-primary">Create Group</a>
  </div>

  <div class="group-container">
    <button class="scroll-button scroll-left" onclick="scrollGroups(-1)">&lt;</button>
    <div class="group-scroll">
      {% for group in groups %}
        <div class="group-card">
          <div class="group-content">
            <div>
              <h3>{{ group.name }}</h3>
              <p>Created by: {{ group.creator.username }}</p>
              <p>{{ group.description }}</p>
              <p>Status: {{ 'Public' if group.public else 'Private' }}</p>
              <form action="{{ url_for('views.delete_group', group_id=group.id) }}" method="POST" style="display:inline;">
                <button type="submit" class="btn btn-danger">Delete Group</button>
            </form>
            </div>
            <div class="group-buttons">
              <!-- <button class="btn btn-danger btn-sm">Delete</button> -->
              <a href="{{ url_for('views.edit_group', group_id=group.id) }}" class="btn btn-warning btn-sm">Edit</a>
              <a href="{{ url_for('views.group_recipes', group_id=group.id) }}" class="btn btn-info btn-sm">View Recipes</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    <button class="scroll-button scroll-right" onclick="scrollGroups(1)">&gt;</button>
  </div>
</div>

<!-- {% endblock %}
<div class="group-list">
    <h2>Groups</h2>
    {% for group in groups %}
    <div class="group-card">
        <h3>{{ group.name }}</h3>
        <p>Created by: {{ group.creator.username }}</p>
        <p>{{ group.description }}</p>
        <p>Status: {{ 'Public' if group.public else 'Private' }}</p>
        <form action="{{ url_for('views.delete_group', group_id=group.id) }}" method="POST" style="display:inline;">
            <button type="submit" class="btn btn-danger">Delete Group</button>
        </form>
        <a href="{{ url_for('views.edit_group', group_id=group.id) }}" class="btn btn-warning">Edit Group</a>
        <a href="{{ url_for('views.group_recipes', group_id=group.id) }}" class="btn btn-info">View Recipes</a>
    </div>
    {% endfor %}
</div> -->

website/templates/landing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Recipe App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                
                    <li class="nav-item">
                        <a class="nav-link" href="/logout">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('views.profile') }}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('views.dashboard') }}">Profile</a>
                    </li>
                
            </ul>
        </div>
    </nav>
    

    <div class="carousel">
        <div class="list">
            <div class="item active" style="--background: #EA3D41">
                <div class="content">Strawberry</div>
                <img src="{{ url_for('static', filename='img/fruit_strawberry.png') }}" class="fruit">
            </div>
            <div class="item" style="--background: #2D5643">
                <div class="content">Avocado</div>
                <img src="{{ url_for('static', filename='img/fruit_avocado.png') }}" class="fruit">
            </div>
            <div class="item hidden" style="--background: #E7A043">
                <div class="content">Orange</div>
                <img src="{{ url_for('static', filename='img/fruit_orange.png') }}" class="fruit">
            </div>
        </div>
        <div class="leaves"></div>
        <div class="mockup"></div>
        <div class="shadow"></div>
        <div class="arrow">
            <button id="prev"><</button>
            <button id="next">></button>
        </div>
    </div>

    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
</body>
</html>

website/templates/my_groups.html
{% extends "base.html" %}

{% block title %}My Groups{% endblock %}

{% block content %}
    <h1>My Groups</h1>
    
    {% if groups %}
        <ul class="list-group">
            {% for group in groups %}
                <li class="list-group-item">
                    <h5>{{ group.name }}</h5>
                    <p>{{ group.description }}</p>
                    {% if group.public %}
                        <span class="badge bg-success">Public</span>
                    {% else %}
                        <span class="badge bg-secondary">Private</span>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>You have not created any groups yet.</p>
    {% endif %}
{% endblock %}